FROM python:3.11

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

HEALTHCHECK --interval=--timeout=30s --start-period=5s --retries=3 CMD [ "executable" ]

ENTRYPOINT [ "executable" ]